version: "3.7"

services:
  button:
    container_name: button
    image: nenavizhuleto/emergency-button:latest
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
    restart: unless-stopped
